
dependencies:
  - OpenZeppelin/openzeppelin-contracts@3.3.0

# automatically fetch contract sources from Etherscan
autofetch_sources: true

compiler:
  solc:
    # version: 0.6.12
    version: 0.7.6
    remappings:
      - "@openzeppelin=OpenZeppelin/openzeppelin-contracts@3.3.0"

